### PR TITLE
Added TLP152

### PR DESCRIPTION
**Pull request by simric**

### CODE REVIEW

**Review by jagjordi — COMMENTED** [review]
Link to the datasheet should be online, now its a local link in your computer

**Comment by jagjordi** [comment]
Fix the link thing, rest looks ok

**Comment by HolgerStenberg** [comment]
Screenshot 2021-01-24 at 15 55 03
Additional: Power in flags can be added

**Review by jagjordi — APPROVED** [review]
Looks good

**Review by HolgerStenberg — APPROVED** [review]

**Pull request merged**
